[project]
name = "cellpose"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jupyterlab>=4.4.10",
    "matplotlib>=3.10.7",
]
